apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager.yaml
  - ./monitoring.yaml
  - ./actions-runner-controller.yaml
  - ./envoy-gateway.yaml
  - ./infra.yaml
  - ./apps.yaml
